### ISSUE TITLE
Upgrade this script to work with SABnzbd also

### ISSUE THREAD

**Issue by H34dl3ss** [Tensai75/ReverseGetPW.py#1]
Would it be possible to have this script adapted so it works with SABnzbd please?

**Comment by Tensai75** [comment]
I don't know if this is possible. Probably yes, but I have never programmed an SABnzbd Extension and honestly I have no intention of doing so. Sorry.

**Comment by H34dl3ss** [comment]
OK, no problem.
The nzbget [issue](https://github.com/nzbgetcom/nzbget/issues/358) will probably be fixed soon so that I can continue with nzbget.
